FROM centos:8
LABEL "Author"="wxdlong@qq.com"
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    yum install -y ansible openssh-server openssh-clients iproute vim man expect && \
    yum clean all


RUN mkdir /var/run/sshd; \
    echo 'root:123456' | chpasswd; \
    ssh-keygen -A ; \
    ssh-keygen -q -N "" -t rsa -f /root/.ssh/id_rsa; \
    cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys; \
    chmod 0600 /root/.ssh/authorized_keys ; \
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

CMD ["/usr/sbin/sshd", "-D"]