- hosts: 127.0.0.1
  connection: local
  name: hello ansible role
  roles:
    - copy

  pre_tasks:
    - name: "hello pre tasks"
      shell: |
        echo "$(date): $(hostname) {{ playbook_dir }}"
  
  post_tasks:
    - name: "hello post tasks"
      shell: |
        echo "$(date): $(hostname)"

  tasks:
    - debug: 
        msg: "current dir: {{ lookup('env','PWD') }} " 
